---
- hosts: "{{ target }}"
  gather_facts: true

  vars:
    solarwinds_info: &solarwinds_info
      hostname: "{{ solarwinds_server }}"
      username: "{{ solarwinds_user }}"
      password: "{{ solarwinds_pass }}"

  tasks:
  - name: Add SNMP node to Solarwinds
    solarwinds.orion.orion_node:
      <<: *solarwinds_info
      state: present
      name: "{{ node_name }}"
      ip_address: "{{ ip_address }}"
      polling_method: SNMP
      polling_engine: "{{ polling_engine }}"
      ro_community_string: "{{ snmp_ro_community_string }}"
    delegate_to: localhost

  - name: Add Linux CPU, Memory, Load Average pollers
    when: ansible_facts['os_family'] != 'Windows'
    solarwinds.orion.orion_node_poller:
      <<: *solarwinds_info
      name: "{{ node_name }}"
      state: present
      poller: "{{ item }}"
      enabled: True
    loop:
      - N.LoadAverage.SNMP.Linux
      - N.Cpu.SNMP.HrProcessorLoad
      - N.Memory.SNMP.NetSnmpReal
    delegate_to: localhost

  - name: Add Linux volumes to node
    when: ansible_facts['os_family'] != 'Windows'
    solarwinds.orion.orion_volume:
      <<: *solarwinds_info
      name: "{{ node_name }}"
      state: present
      volume:
        name: "{{ item }}"
    loop:
      - /
      - /opt
      - /var
      - /boot
      - /home
      - /var/log
    delegate_to: localhost

  - name: Discover and add Linux interfaces
    when: ansible_facts['os_family'] != 'Windows'
    solarwinds.orion.orion_node_interface:
      <<: *solarwinds_info
      name: "{{ node_name }}"
      state: present
      interface: "{{ item }}"
    loop:
      - eth0
      - eth1
      - eth2
    delegate_to: localhost

  - name: Add Windows SNMP pollers
    when: ansible_facts['os_family'] = 'Windows'
    solarwinds.orion.orion_node_poller:
      <<: *solarwinds_info
      name: "{{ node_name }}"
      state: present
      poller: "{{ item.name }}"
      enabled: "{{ item.enabled }}"
    loop:
      - name: N.Cpu.SNMP.HrProcessorLoad
        enabled: True
      - name: N.Memory.SNMP.NetSnmpReal
        enabled: True
    delegate_to: localhost

# I use regex matching for Windows interfaces, as SNMP seems to report the full device name.
  - name: Add Windows interfaces
    when: ansible_facts['os_family'] != 'Windows'
    solarwinds.orion.orion_node_interface:
      <<: *solarwinds_info
      name: "{{ node_name }}"
      state: present
      interface: "{{ item }}"
    loop:
      - "Ethernet$"
      - "Ethernet 1$"
      - "Ethernet 2$"
    delegate_to: localhost

# Windows Volumes with SNMP are reported with Serial Number. Currently, Volume module doesn't do volume discovery, so it is omitted.
