---
- name: Add hosts as nodes to Solarwinds as SNMPv2
  hosts: "{{ target }}"
  gather_facts: true # if you don't want to use ansible facts, make sure to then override default caption and IP variables

  vars: # Be sure to check out the role README for a full list of variables
    solarwinds_server: 127.0.0.1
    solarwinds_username: admin
    solarwinds_password: changeme2345
    linux_node_polling_method: SNMP
    linux_node_snmp_version: 2
    linux_node_ro_community_string: community
    linux_node_snmp_pollers: # the role already will add some default pollers, this is example of adding others
      - name: N.Topology_Layer3.SNMP.ipNetToMedia
        enabled: false
    linux_node_custom_properties:
      - name: Server_Environment
        value: Production
    linux_node_discover_interfaces: true
    linux_node_volumes:
      - /
      - /home
      - /var/log

  roles:
     - { role: solarwinds.orion.linux_node }

